//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSHelpLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HelpTicket()
        {
            this.StatusId = 1;
        }
    
        public int HelpTicketId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> InstructorId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime TimeIn { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TimeDone { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Location Location { get; set; }
        public virtual Status Status { get; set; }
        public virtual Student Student { get; set; }
    }
}
